Dingfan colored navbar
ucsb-cs156-s23/proj-gauchoride-s23-5pm-3 pull request #26
Opened 2023-06-01 00:32 UTC by dingfan123

Changed the navbar color to Hex color: #003660
<img width="1440" alt="Screenshot 2023-05-31 at 5 31 17 PM" src="https://github.com/ucsb-cs156-s23/proj-gauchoride-s23-5pm-3/assets/86548264/e9f424e8-3349-47ee-a5d2-01cfba837ad5">

2023-06-01 19:42 UTC, seannoh requested changes

2023-06-01 19:42 UTC, seannoh commented on frontend/package-lock.json
There shouldn't be committed changes to package-lock.json.
Other than that, LGTM

2023-06-01 20:18 UTC, dingfan123 commented on frontend/package-lock.json
Fixed

2023-06-01 20:33 UTC, seannoh approved these changes

2023-06-04 19:23 UTC, pconrad approved these changes
LGTM

2023-06-04 19:23 UTC, merged