Added database for Driver Shifts
ucsb-cs156-s23/proj-gauchoride-s23-5pm-3 pull request #32
Opened 2023-06-01 21:18 UTC by ivanke1

Added @Entity and @Repository classes for driver shifts

2023-06-01 21:35 UTC, seannoh requested changes

2023-06-01 21:35 UTC, seannoh commented on src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverShift.java
> +  private String backupDriver;
remove backupDriver for now, we'll implement a way for drivers to set this up on the frontend later

2023-06-01 22:02 UTC, seannoh approved these changes

2023-06-04 19:44 UTC, pconrad approved these changes
LGTM!

2023-06-04 19:44 UTC, merged